version: "3"
services:
  reverseproxy:
<<<<<<< HEAD
      image: andriesekt/reverseproxy
=======
      image: scheele/reverseproxy
>>>>>>> 13942c4c9f0a7b77fb912411388e70ddc20b085b
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed     
  backend-user:
<<<<<<< HEAD
    image: andriesekt/udacity-restapi-user
=======
    image: scheele/udacity-restapi-user
>>>>>>> 13942c4c9f0a7b77fb912411388e70ddc20b085b
    environment:
      POSTGRESS_USERNAME: $POSTGRESS_USERNAME
      POSTGRESS_PASSWORD: $POSTGRESS_PASSWORD 
      POSTGRESS_DB: $POSTGRESS_DB 
      POSTGRESS_HOST: $POSTGRESS_HOST 
      AWS_REGION: $AWS_REGION 
      AWS_PROFILE: $AWS_PROFILE 
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
  backend-feed:
<<<<<<< HEAD
    image: andriesekt/udacity-restapi-feed
=======
    image: scheele/udacity-restapi-feed
>>>>>>> 13942c4c9f0a7b77fb912411388e70ddc20b085b
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRESS_USERNAME: $POSTGRESS_USERNAME
      POSTGRESS_PASSWORD: $POSTGRESS_PASSWORD 
      POSTGRESS_DB: $POSTGRESS_DB 
      POSTGRESS_HOST: $POSTGRESS_HOST 
      AWS_REGION: $AWS_REGION 
      AWS_PROFILE: $AWS_PROFILE 
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
  frontend:
<<<<<<< HEAD
    image: andriesekt/udacity-frontend:local
    ports:
      - "8100:80"
=======
    image: scheele/udacity-frontend:local
    ports:
      - "8100:80"
>>>>>>> 13942c4c9f0a7b77fb912411388e70ddc20b085b
